const actionTypes = {
  GET_DATA_START: "GET_DATA_START",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",
  GET_CATEGORIES_START: "GET_GET_CATEGORIES_START",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORY_START: "GET_GET_CATEGORY_START",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  DECREASE_FROM_BASKET: "DECREASE_FROM_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
};

export default actionTypes;
